# Target type:
# - standard_rank1: Standard rank-1 problem
# - incremental_rank1: Incremental rank-1 problem
target_type: incremental_rank1

# Stopping criterion:
# - std: Classical bisection method (based on interval length |b - a| ≤ 2εmax(1, |a|, |b|))
# - gu: Gu-Eisenstat method (based on function value |g(μ)| ≤ ε(1 + sum_terms))
stop_criterion: gu